services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ..:/var/www/html
      - ./php/log:/var/log/php
    working_dir: /var/www/html/public
    ports:
      - "9000:9000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ..:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
  mysql:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./mysql_data:/var/lib/mysql
      ports:
        - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: ["--requirepass", "verlit", "--appendonly", "yes"]